export const COLOMBIA_CITIES = [
  "Abrego",
  "Aguachica",
  "Aguadas",
  "Ambalema",
  "Andalucia",
  "Anserma",
  "Ansermanuevo",
  "Apartado",
  "Aracataca",
  "Arauca",
  "Arjona",
  "Armenia",
  "Barbacoas",
  "Barrancabermeja",
  "Barranquilla",
  "Belen de Umbria",
  "Bello",
  "Bogota D.C.",
  "Bosconia",
  "Bucaramanga",
  "Buenaventura",
  "Buga",
  "Bugalagrande",
  "Cajica",
  "Calarca",
  "Caldas",
  "Cali",
  "Candelaria",
  "Cartagena",
  "Cartago",
  "Caucasia",
  "Cerete",
  "Chaparral",
  "Chia",
  "Chigorodo",
  "Chinacota",
  "Chinchina",
  "Chinu",
  "Chiquinquira",
  "Ciénaga",
  "Circasia",
  "Codazzi",
  "Convencion",
  "Copacabana",
  "Cucuta",
  "Cucutilla",
  "Dosquebradas",
  "Duitama",
  "El Banco",
  "El Bagre",
  "El Bordo Patia",
  "El Carmen",
  "El Cerrito",
  "El Charco",
  "El Retiro",
  "El Santuario",
  "El Zulia",
  "Envigado",
  "Espinal",
  "Facatativa",
  "Filandia",
  "Flandes",
  "Floridablanca",
  "Florencia",
  "Fonseca",
  "Fresno",
  "Fundacion",
  "Funza",
  "Fusagasuga",
  "Garagoa",
  "Ginebra",
  "Girardot",
  "Girardota",
  "Guacari",
  "Guamo",
  "Guarne",
  "Guateque",
  "Hacari",
  "Herran",
  "Honda",
  "Ibague",
  "Inirida",
  "Ipiales",
  "Itagui",
  "Jamundi",
  "La Ceja",
  "La Cruz",
  "La Dorada",
  "La Estrella",
  "La Jagua de Ibirico",
  "La Playa",
  "La Tebaida",
  "La Union",
  "La Union Narino",
  "La Virginia",
  "Leticia",
  "Libano",
  "Lorica",
  "Los Patios",
  "Madrid",
  "Magangue",
  "Maicao",
  "Manizales",
  "Manzanares",
  "Marinilla",
  "Mariquita",
  "Marsella",
  "Medellin",
  "Melgar",
  "Mercaderes",
  "Mocoa",
  "Moniquira",
  "Montelibano",
  "Monteria",
  "Montenegro",
  "Mosquera",
  "Necocli",
  "Neiva",
  "Nobsa",
  "Ocana",
  "Paipa",
  "Palmira",
  "Pamplona",
  "Pasto",
  "Pereira",
  "Piendamo",
  "Planeta Rica",
  "Plato",
  "Popayan",
  "Puerto Berrio",
  "Puerto Boyaca",
  "Puerto Carreno",
  "Puerto Santander",
  "Puerto Tejada",
  "Purificacion",
  "Quibdo",
  "Quimbaya",
  "Remedios",
  "Ricaurte Narino",
  "Riohacha",
  "Rionegro",
  "Riosucio",
  "Roldanillo",
  "Sabaneta",
  "Sahagun",
  "Salamina",
  "Salento",
  "Samaniego",
  "San Andres",
  "San Calixto",
  "San Jose del Guaviare",
  "San Juan del Cesar",
  "Sandona",
  "Santa Marta",
  "Santa Rosa de Cabal",
  "Santander de Quilichao",
  "Sardinata",
  "Segovia",
  "Sevilla",
  "Silvia",
  "Sincelejo",
  "Soacha",
  "Soledad",
  "Sogamoso",
  "Teorama",
  "Tibu",
  "Tierralta",
  "Timbio",
  "Toledo",
  "Toro",
  "Tulua",
  "Tumaco",
  "Tunja",
  "Tuquerres",
  "Turbaco",
  "Turbo",
  "Valledupar",
  "Villa de Leyva",
  "Villa del Rosario",
  "Villa Rica",
  "Villamaria",
  "Villanueva",
  "Villavicencio",
  "Yopal",
  "Yumbo",
  "Zaragoza",
  "Zarzal",
  "Zipaquira",
];
